=== VV01T3K/PG-HiH-2023/xml_example/cos/HiH.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" attributeFormDefault="unqualified" elementFormDefault="qualified">
    <xs:element name="dogpedia" type="dogpediaType" />

    <xs:complexType name="dogpediaType">
        <xs:sequence>
            <xs:element name="author" type="authorType" />
            <xs:element name="dogs" type="dogsType" />
            <xs:element name="brands" type="brandsType" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="authorType">
        <xs:all>
            <xs:element ref="name" />
            <xs:element name="surname" type="xs:string" />
            <xs:element name="number" type="numberType" />
            <xs:element name="group" type="xs:integer" />
        </xs:all>
        <xs:attribute ref="liked" use="required" />
    </xs:complexType>

    <xs:complexType name="dogsType">
        <xs:sequence>
            <xs:element name="blue">
                <xs:complexType>
                    <xs:complexContent>
                        <xs:extension base="dogType">
                            <xs:sequence>
                                <xs:element name="dailyroutine">
                                    <xs:complexType>
                                        <xs:sequence>
                                            <xs:element name="excercise">
                                                <xs:complexType>
                                                    <xs:sequence>
                                                        <xs:element name="walks" type="xs:string" />
                                                        <xs:element name="playing" type="xs:string" />
                                                    </xs:sequence>
                                                </xs:complexType>
                                            </xs:element>
                                            <xs:element name="meals">
                                                <xs:complexType>
                                                    <xs:sequence>
                                                        <xs:element name="description" type="xs:string" />
                                                        <xs:element name="times">
                                                            <xs:simpleType>
                                                                <xs:restriction>
                                                                    <xs:simpleType>
                                                                        <xs:list>
                                                                            <xs:simpleType>
                                                                                <xs:restriction base="xs:time">
                                                                                    <xs:minInclusive value="05:00:00" />
                                                                                </xs:restriction>
                                                                            </xs:simpleType>
                                                                        </xs:list>
                                                                    </xs:simpleType>
                                                                    <xs:length value="3" />
                                                                </xs:restriction>
                                                            </xs:simpleType>
                                                        </xs:element>
                                                    </xs:sequence>
                                                </xs:complexType>
                                            </xs:element>
                                            <xs:element name="sleep">
                                                <xs:complexType>
                                                    <xs:sequence>
                                                        <xs:element name="amount" type="xs:string" />
                                                        <xs:element name="places">
                                                            <xs:complexType>
                                                                <xs:sequence>
                                                                    <xs:element name="place" maxOccurs="unbounded">
                                                                        <xs:complexType>
                                                                            <xs:simpleContent>
                                                                                <xs:extension base="xs:string">
                                                                                    <xs:attribute name="daytime" use="required" type="ynType" />
                                                                                    <xs:attribute name="nighttime" use="required" type="ynType" />
                                                                                </xs:extension>
                                                                            </xs:simpleContent>
                                                                        </xs:complexType>
                                                                    </xs:element>
                                                                </xs:sequence>
                                                            </xs:complexType>
                                                        </xs:element>
                                                    </xs:sequence>
                                                </xs:complexType>
                                            </xs:element>
                                        </xs:sequence>
                                    </xs:complexType>
                                </xs:element>
                            </xs:sequence>
                        </xs:extension>
                    </xs:complexContent>
                </xs:complexType>
            </xs:element>
            <xs:element name="dog" type="dogType" maxOccurs="unbounded" />
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="brandsType">
        <xs:sequence>
            <xs:element name="brand" maxOccurs="unbounded">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element ref="name" />
                        <xs:element name="about">
                            <xs:simpleType>
                                <xs:restriction base="xs:string">
                                    <xs:minLength value="100" />
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:element>
                        <xs:element name="products">
                            <xs:complexType>
                                <xs:sequence>
                                    <xs:element name="product" maxOccurs="unbounded">
                                        <xs:complexType>
                                            <xs:sequence>
                                                <xs:element name="productName" type="xs:string" />
                                                <xs:element name="price" type="priceType" />
                                                <xs:element name="link" type="imglinkType" />
                                            </xs:sequence>
                                        </xs:complexType>
                                    </xs:element>
                                </xs:sequence>
                            </xs:complexType>
                        </xs:element>
                    </xs:sequence>
                    <xs:attribute name="category" use="required">
                        <xs:simpleType>
                            <xs:restriction base="xs:string">
                                <xs:enumeration value="accessories" />
                                <xs:enumeration value="food and treats" />
                            </xs:restriction>
                        </xs:simpleType>
                    </xs:attribute>
                    <xs:attribute ref="liked" use="required" />
                </xs:complexType>
            </xs:element>
        </xs:sequence>
    </xs:complexType>

    <xs:complexType name="dogType">
        <xs:sequence>
            <xs:element ref="name" />
            <xs:element name="breed">
                <xs:complexType>
                    <xs:choice>
                        <xs:element name="known" type="xs:string" />
                        <xs:element name="unknown">
                            <xs:simpleType>
                                <xs:restriction base="xs:string">
                                    <xs:enumeration value="unknown" />
                                </xs:restriction>
                            </xs:simpleType>
                        </xs:element>
                    </xs:choice>
                </xs:complexType>
            </xs:element>
            <xs:element name="image" type="imglinkType" minOccurs="0" maxOccurs="1" />
            <xs:element name="birth" type="xs:gYear" />
            <xs:element name="death" type="xs:gYear" minOccurs="0" maxOccurs="1" />
            <xs:element name="color" type="xs:string" />
            <xs:element name="home" type="xs:string" />
            <xs:element name="friends" minOccurs="0" maxOccurs="1">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="friend" type="nameType" maxOccurs="unbounded" />
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="enemies" minOccurs="0" maxOccurs="1">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="enemy" type="nameType" maxOccurs="unbounded" />
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="nicknames" minOccurs="0" maxOccurs="1">
                <xs:complexType>
                    <xs:sequence>
                        <xs:element name="nickname" type="xs:string" maxOccurs="unbounded" />
                    </xs:sequence>
                </xs:complexType>
            </xs:element>
            <xs:element name="cuddly" type="xs:boolean" />
        </xs:sequence>
        <xs:attributeGroup ref="dogAttributes" />
    </xs:complexType>

    <xs:complexType name="imglinkType">
        <xs:simpleContent>
            <xs:extension base="xs:string">
                <xs:attribute name="source" type="xs:anyURI" use="required" />
            </xs:extension>
        </xs:simpleContent>
    </xs:complexType>

    <xs:simpleType name="priceType">
        <xs:restriction base="xs:decimal">
            <xs:fractionDigits value="2" />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="ynType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="yes" />
            <xs:enumeration value="no" />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="nameType">
        <xs:restriction base="xs:string">
            <xs:maxLength value="10" />
            <xs:minLength value="1" />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="numberType">
        <xs:restriction base="xs:integer">
            <xs:pattern value="[0-9][0-9][0-9][0-9][0-9][0-9]" />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="earsType">
        <xs:restriction base="xs:string">
            <xs:enumeration value="droopy" />
            <xs:enumeration value="upright" />
        </xs:restriction>
    </xs:simpleType>

    <xs:simpleType name="notNegativeType">
        <xs:restriction base="xs:integer">
            <xs:minInclusive value="0" />
        </xs:restriction>
    </xs:simpleType>

    <xs:attributeGroup name="dogAttributes">
        <xs:attribute name="alive" use="required" type="ynType" />
        <xs:attribute name="paws" use="required" type="notNegativeType"></xs:attribute>
        <xs:attribute name="tails" use="required" type="notNegativeType"></xs:attribute>
        <xs:attribute name="ears" use="required">
            <xs:simpleType>
                <xs:union memberTypes="earsType ynType" />
            </xs:simpleType>
        </xs:attribute>
        <xs:attribute name="bark" use="required" type="ynType" />
    </xs:attributeGroup>

    <xs:attribute name="liked" type="ynType" />

    <xs:element name="name" type="nameType" />

</xs:schema>

=== VV01T3K/PG-HiH-2023/xml_example/cos/HiH(xsd).xml
<?xml version="1.0" encoding="utf-8"?>
<dogpedia xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="HiH.xsd">

    <author liked="yes">
        <name>...</name>
        <surname>...</surname>
        <group>...</group>
        <number>...</number>
    </author>

    <dogs>
        <blue alive="yes" paws="4" tails="1" ears="droopy" bark="yes">
            <name>Blueberry</name>
            <breed>
                <known>Maltipoo</known>
            </breed>
            <image source="...">photo of Blue</image>
            <birth>2021</birth>
            <color>white, black and blonde</color>
            <home>Gda≈Ñsk</home>
            <friends>
                <friend>Benji</friend>
                <friend>Frania</friend>
                <friend>Kiara</friend>
                <friend>Odie</friend>
            </friends>
            <enemies>
                <enemy>Nela</enemy>
            </enemies>
            <nicknames>
                <nickname>x</nickname>
                <nickname>y</nickname>
                <nickname>z</nickname>
            </nicknames>
            <cuddly>true</cuddly>

            <dailyroutine>
                <excercise>
                    <walks>at least 3 times a day for 10-30 minutes</walks>
                    <playing>playing with toys and searching for treats</playing>
                </excercise>
                <meals>
                    <description>3 a day, 40 grams of dry food consisting of various meats, wheat, rice, fruits, yeast and more</description>
                    <times>07:50:00 14:30:00 19:00:00</times>
                </meals>
                <sleep>
                    <amount>about 7 hours during the night and very many naps during the day</amount>
                    <places>
                        <place daytime="yes" nighttime="no">dog bed</place>
                        <place daytime="yes" nighttime="no">blanket</place>
                        <place daytime="yes" nighttime="no">couch</place>
                        <place daytime="yes" nighttime="no">bed</place>
                        <place daytime="yes" nighttime="yes">floor</place>
                        <place daytime="no" nighttime="yes">pillow</place>
                    </places>
                </sleep>
            </dailyroutine>
        </blue>

        <dog alive="yes" paws="4" tails="1" ears="upright" bark="no">
            <name>Benji</name>
            <breed>
                <known>Basenji</known>
            </breed>
            <image source="...">photo of Benji</image>
            <birth>2022</birth>
            <color>brown, white</color>
            <home>...</home>
            <friends>
                <friend>Figa</friend>
                <friend>Blueberry</friend>
            </friends>
            <nicknames>
                <nickname>x</nickname>
                <nickname>y</nickname>
                <nickname>z</nickname>
            </nicknames>
            <cuddly>false</cuddly>
        </dog>

        <dog alive="yes" paws="4" tails="1" ears="upright" bark="yes">
            <name>Diego</name>
            <breed>
                <known>German Shepherd</known>
            </breed>
            <image source="...">photo of Diego</image>
            <birth>2020</birth>
            <color>black, brown</color>
            <home>...</home>
            <friends>
                <friend>Miauczuk</friend>
            </friends>
            <enemies>
                <enemy>every dog</enemy>
            </enemies>
            <nicknames>
                <nickname>x</nickname>
                <nickname>y</nickname>
                <nickname>z</nickname>
            </nicknames>
            <cuddly>false</cuddly>
        </dog>

        <dog alive="no" paws="4" tails="1" ears="droopy" bark="yes">
            <name>Shati</name>
            <breed>
                <known>Yorkshire Terrier</known>
            </breed>
            <birth>2008</birth>
            <death>2019</death>
            <color>black, brown</color>
            <home>...</home>
            <nicknames>
                <nickname>x</nickname>
                <nickname>y</nickname>
                <nickname>z</nickname>
            </nicknames>
            <cuddly>true</cuddly>
        </dog>

        <dog alive="yes" paws="1" tails="2" ears="no" bark="yes">
            <name>Burek</name>
            <breed>
                <unknown>unknown</unknown>
            </breed>
            <birth>2015</birth>
            <color>yellow</color>
            <home>...</home>
            <friends>
                <friend>Azor</friend>
                <friend>Fafik</friend>
                <friend>Tofik</friend>
            </friends>
            <cuddly>false</cuddly>
        </dog>
    </dogs>

    <brands>
        <brand category="accessories" liked="yes">
            <name>Trixie</name>
            <about>
                Trixie is a brand of accessories for dogs such as: leashes, dog harnesses, bowls, transporters, toys, dog care products and much more. They have been around since 1974 and have maintained a very good reputation ever since.
            </about>
            <products>
                <product>
                    <productName>medium dog poop bags 4 rolls</productName>
                    <price>7.99</price>
                    <link source="https://animalia.pl/trixie-4-rolki-torebek-na-psie-odchody-czarne-4x-20-szt/szczegoly/20689/">product page</link>
                </product>
                <product>
                    <productName>ball 6cm</productName>
                    <price>11.10</price>
                    <link source="https://animalia.pl/trixie-pilki-pyszczki-6-cm/szczegoly/3024/">product page</link>
                </product>
                <product>
                    <productName>eye cleaninig pads - 100pcs</productName>
                    <price>28.25</price>
                    <link source="https://animalia.pl/trixie-eye-care-platki-do-czyszczenia-oczu-w-pojemniku-100-szt/szczegoly/42499/">product page</link>
                </product>
                <product>
                    <productName>large diapers for puppies - 10pcs</productName>
                    <price>25.25</price>
                    <link source="https://animalia.pl/trixie-pieluchy-dla-szczeniat-duze-60-x-60-cm-10-szt/szczegoly/21643/">product page</link>
                </product>
                <product>
                    <productName>toothbrush for dogs - 2pcs</productName>
                    <price>5.90</price>
                    <link source="https://animalia.pl/trixie-szczotki-do-zebow-i-masazu-zakladane-na-palec-2-szt/szczegoly/3118/">product page</link>
                </product>
            </products>
        </brand>

        <brand category="food and treats" liked="yes">
            <name>Brit</name>
            <about>
                Brit is a brand of dog food and treats. They offer a wide variety of products, which contain from salmon to lamb. This brand puts emphasis on providing a well balanced diet for pets, which is why the food they sell contains vitamins and all essential nutrients that dogs need.
            </about>
            <products>
                <product>
                    <productName>Brit Vitamins - Multivitamin 150g</productName>
                    <price>59.00</price>
                    <link source="https://karmybrit.pl/brit-care-cat-paste-anti-hairball-with-taurine-pasta-dla-doroslych-kotow-odklaczajaca-z-tauryna-100g-6.html">product page</link>
                </product>
                <product>
                    <productName>BRIT CARE DOG CRUNCHY CRACKER INSECT AND SALMON 200g </productName>
                    <price>17.00</price>
                    <link source="https://karmybrit.pl/brit-care-dog-crunchy-cracker-insects-rich-in-salmon-enriched-with-thyme.html">product page</link>
                </product>
                <product>
                    <productName>Brit Premium by Nature Lamb with Buckwheat 400g</productName>
                    <price>6.10  </price>
                    <link source="https://karmybrit.pl/brit-premium-by-nature-lamb-with-buckwheat.html">product page</link>
                </product>
                <product>
                    <productName>BRIT CARE DOG FUNCTIONAL SNACK SHRIMP ANTISTRESS 150G</productName>
                    <price>15.00</price>
                    <link source="https://karmybrit.pl/brit-care-dog-functional-snack-shrimp-antistress-150g.html">product page</link>
                </product>
                <product>
                    <productName>BRIT FRESH chicken with potatoes for puppies of all breeds 2,5kg</productName>
                    <price>58.00</price>
                    <link source="https://karmybrit.pl/brit-fresh-kurczak-z-ziemniakami-dla-szczeniat-wszystkich-ras.html">product page</link>
                </product>
            </products>
        </brand>


    </brands>

</dogpedia>
