<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE valorant_state [
    <!ELEMENT valorant_state (ranks, teams, tournaments)>

    <!ELEMENT name (#PCDATA)>
    <!ELEMENT teams (team+)>

    <!ENTITY both_handed "ambidextrous">

    <!ENTITY FHD "1920 x 1080">
    <!ENTITY QHD "2560 x 1440">
    <!ENTITY UHD "3840 x 2160">


    <!ELEMENT ranks (rank*)>
    <!ELEMENT rank (name,divisions, image, playerbase_percent)>
    <!ELEMENT divisions (#PCDATA)>
    <!ELEMENT image (#PCDATA)>
    <!ATTLIST image src CDATA #REQUIRED>
    <!ELEMENT playerbase_percent (#PCDATA)>

    <!ELEMENT team (name , players?)>
    <!ATTLIST team id ID #REQUIRED>
    <!ELEMENT players (player*)>
    <!ELEMENT player (username, player_rank, server?, personal_info?, socials? ,favourites?)>
    <!ATTLIST player id ID #REQUIRED>
    <!ATTLIST player active (yes|no) #REQUIRED>
    <!ELEMENT username (#PCDATA)>
    <!ATTLIST username gametag CDATA #REQUIRED>
    <!ELEMENT player_rank (#PCDATA)>
    <!ATTLIST player_rank division CDATA #IMPLIED>
    <!ELEMENT server (#PCDATA)>
    <!ATTLIST server avg_ping CDATA #IMPLIED>
    <!ELEMENT personal_info (fullname, age, country)>
    <!ATTLIST personal_info access (limited|free|prohibited) "limited">
    <!ELEMENT fullname (#PCDATA)>
    <!ELEMENT age (#PCDATA)>
    <!ELEMENT country (#PCDATA)>
    <!ELEMENT socials (link*)>
    <!ELEMENT link (#PCDATA)>
    <!ATTLIST link src CDATA #REQUIRED>
    <!ELEMENT favourites (weapon?, agent?, mouse?, keyboard?, monitor?)>
    <!ELEMENT weapon (name,skin*)>
    <!ELEMENT skin (#PCDATA)>
    <!ATTLIST skin src CDATA #REQUIRED>
    <!ATTLIST skin upgraded (yes|no) #REQUIRED>
    <!ELEMENT agent (#PCDATA)>
    <!ELEMENT mouse (#PCDATA)>
    <!ATTLIST mouse mousepad (yes|no) #REQUIRED>
    <!ATTLIST mouse type CDATA #REQUIRED>
    <!ATTLIST mouse dpi CDATA #REQUIRED>
    <!ELEMENT keyboard (#PCDATA)>
    <!ATTLIST keyboard type CDATA #REQUIRED>
    <!ELEMENT monitor (name, size, panel, resolution, refresh_rate)>
    <!ATTLIST monitor model CDATA #REQUIRED>
    <!ELEMENT size (#PCDATA)>
    <!ELEMENT panel (#PCDATA)>
    <!ATTLIST panel sync_tech CDATA "FreeSync">
    <!ELEMENT resolution (#PCDATA)>
    <!ELEMENT refresh_rate (#PCDATA)>

    <!ELEMENT tournaments (tournament*)>
    <!ELEMENT tournament (name, location, date, prize_pool, teams)>
    <!ELEMENT location (#PCDATA)>
    <!ELEMENT date (#PCDATA)>
    <!ELEMENT prize_pool (#PCDATA)>
    <!ATTLIST prize_pool currency CDATA "PLN">
]>

<valorant_state>
    <ranks>
        <rank>
            <name>Immortal</name>
            <divisions> 1 2 3 </divisions> <!-- list -->
            <image src="...">immortal</image>
            <playerbase_percent>3%</playerbase_percent>
        </rank>
        <rank>
            <name>Radiant</name>
            <divisions> 1 </divisions> <!-- list -->
            <image src="...">radiant</image>
            <playerbase_percent>2%</playerbase_percent>
        </rank>
    </ranks>
    <teams>
        <team id="team-1">
            <name>Team 1</name>
            <players>
                <player id="player-1" active="yes">
                    <username gametag="1234">Player 1</username>
                    <player_rank division="1">Gold</player_rank>
                    <server avg_ping="20">EU</server>
                    <personal_info access="prohibited">
                        <fullname>Adam Sandler</fullname>
                        <age>28</age>
                        <country>Poland</country>
                    </personal_info>
                    <socials>
                        <link src="https://twitter.com/">Twitter | X</link>
                        <link src="https://instagram.com/">Instagram</link>
                        <link src="https://facebook.com/">Facebook</link>
                    </socials>
                    <favourites>
                        <weapon>
                            <name>Phantom</name>
                            <skin src="..." upgraded="yes">Prime</skin>
                        </weapon>
                        <agent>Jett</agent>
                        <mouse mousepad="yes" type="&both_handed;" dpi="1800">Logitech G Pro</mouse>
                        <keyboard type="mechanical">Logitech G Pro</keyboard>
                        <monitor model="XL2546">
                            <name>BenQ Zowie</name>
                            <size>27"</size>
                            <panel sync_tech="G-Sync">IPS</panel>
                            <resolution>&QHD;</resolution>
                            <refresh_rate>240Hz</refresh_rate>
                        </monitor>
                    </favourites>
                </player>
            </players>
        </team>
    </teams>
    <tournaments>
        <tournament>
            <name>Valorant Masters</name>
            <location>Reykjavik, Iceland</location>
            <date>May 24-30, 2021</date>
            <prize_pool currency="$">600,000</prize_pool>
            <teams>
                <team id="team_1">
                    <name>Team 1</name>
                </team>
                <team id="team_2">
                    <name>Team 2</name>
                </team>
            </teams>
        </tournament>
    </tournaments>
</valorant_state>