<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE valorant_state [
    <!ELEMENT valorant_state (ranks, teams, tournaments)>


    <!ENTITY both_handed "ambidextrous">

    <!ENTITY FHD "1920 x 1080">
    <!ENTITY QHD "2560 x 1440">
    <!ENTITY UHD "3840 x 2160">

    <!ELEMENT name (#PCDATA | edition)*>
    <!ELEMENT teams (team+)>

    <!ELEMENT ranks (rank*)>
    <!ELEMENT rank (name,divisions, image, playerbase_percent)>
    <!ELEMENT divisions (#PCDATA)>
    <!ELEMENT image (#PCDATA)>
    <!ATTLIST image src CDATA #REQUIRED>
    <!ELEMENT playerbase_percent (#PCDATA)>

    <!ELEMENT team (name , players?)>
    <!ATTLIST team id ID #REQUIRED>
    <!ELEMENT players (player*)>
    <!ELEMENT player (username, player_rank, server?, personal_info?, socials? ,favourites?, experience?)>
    <!ATTLIST player id ID #REQUIRED>
    <!ATTLIST player active (yes|no) #REQUIRED>
    <!ELEMENT username (#PCDATA)>
    <!ATTLIST username gametag CDATA #REQUIRED>
    <!ELEMENT player_rank (#PCDATA)>
    <!ATTLIST player_rank division CDATA #IMPLIED>
    <!ELEMENT server (#PCDATA)>
    <!ATTLIST server avg_ping CDATA #IMPLIED>
    <!ELEMENT personal_info (fullname, age, country)>
    <!ATTLIST personal_info access (limited|free|prohibited) "limited">
    <!ELEMENT fullname (#PCDATA)>
    <!ELEMENT age (#PCDATA)>
    <!ELEMENT country (#PCDATA)>
    <!ELEMENT socials (link*)>
    <!ELEMENT link (#PCDATA)>
    <!ATTLIST link url CDATA #REQUIRED>
    <!ELEMENT favourites (weapon?, agent?, (mouse | tablet)?, keyboard?, monitor?)>
    <!ELEMENT weapon (name,skin*)>
    <!ELEMENT skin (#PCDATA)>
    <!ATTLIST skin src CDATA #REQUIRED>
    <!ATTLIST skin upgraded (yes|no) #REQUIRED>
    <!ELEMENT agent (#PCDATA)>
    <!ELEMENT mouse (#PCDATA)>
    <!ATTLIST mouse type CDATA #IMPLIED>
    <!ELEMENT tablet (#PCDATA)>
    <!ELEMENT keyboard (#PCDATA)>
    <!ELEMENT monitor (name, size, panel, resolution, refresh_rate)>
    <!ATTLIST monitor model CDATA #REQUIRED>
    <!ELEMENT size (#PCDATA)>
    <!ELEMENT panel (#PCDATA)>
    <!ATTLIST panel sync_tech CDATA "FreeSync">
    <!ELEMENT resolution (#PCDATA)>
    <!ELEMENT refresh_rate (#PCDATA)>
    <!ELEMENT experience (#PCDATA)>

    <!ELEMENT tournaments (tournament*)>
    <!ELEMENT tournament (name, location, date, prize_pool, teams)>
    <!ELEMENT location (#PCDATA)>
    <!ELEMENT date (start, end)>
    <!ELEMENT start (#PCDATA)>
    <!ELEMENT end (#PCDATA)>
    <!ELEMENT prize_pool (#PCDATA)>
    <!ATTLIST prize_pool currency CDATA "PLN">
    <!ELEMENT edition (#PCDATA)>
]>

<valorant_state>

    <ranks>
        <rank>
            <name>Platinum</name>
            <divisions>1 2 3</divisions>
            <image src="server/iamge">platinum</image>
            <playerbase_percent>30</playerbase_percent>
        </rank>
        <rank>
            <name>Diamond</name>
            <divisions>1 2 3</divisions>
            <image src="server/iamge">diamond</image>
            <playerbase_percent>15</playerbase_percent>
        </rank>
        <rank>
            <name>Ascendant</name>
            <divisions>1 2 3</divisions>
            <image src="server/iamge">ascendant</image>
            <playerbase_percent>8</playerbase_percent>
        </rank>
        <rank>
            <name>Immortal</name>
            <divisions>1 2 3</divisions>
            <image src="server/iamge">immortal</image>
            <playerbase_percent>5</playerbase_percent>
        </rank>
        <rank>
            <name>Radiant</name>
            <divisions>1</divisions>
            <image src="server/iamge">radiant</image>
            <playerbase_percent>1</playerbase_percent>
        </rank>
    </ranks>
    <teams>
        <team id="team-1">
            <name>Team 1</name>
            <players>
                <player id="player-1" active="yes">
                    <username gametag="1234">Player 1</username>
                    <player_rank division="1">Gold</player_rank>
                    <server avg_ping="20">EU</server>
                    <personal_info access="prohibited">
                        <fullname>Adam Sandler</fullname>
                        <age>28</age>
                        <country>Poland</country>
                    </personal_info>
                    <socials>
                        <link url="https://instagram.com/">Instagram</link>
                    </socials>
                    <favourites>
                        <weapon>
                            <name>Phantom</name>
                            <skin src="server/iamge" upgraded="yes">Prime</skin>
                        </weapon>
                        <agent>Jett</agent>
                        <tablet>Wacom Intuos Pro</tablet>
                        <keyboard>Logitech G Pro</keyboard>
                        <monitor model="XL2546">
                            <name>BenQ Zowie</name>
                            <size>27"</size>
                            <panel sync_tech="G-Sync">IPS</panel>
                            <resolution>2560 x 1440</resolution>
                            <refresh_rate>240Hz</refresh_rate>
                        </monitor>
                    </favourites>
                    <experience>562354</experience>
                </player>
                <player id="player-2" active="no">
                    <username gametag="1234">Player 2</username>
                    <player_rank division="1">Gold</player_rank>
                    <server avg_ping="20">EU</server>
                    <personal_info access="prohibited">
                        <fullname>Adam Sandler</fullname>
                        <age>dwadzie≈õcia</age>
                        <country>Poland</country>
                    </personal_info>
                    <socials>
                        <link url="https://twitter.com/">Twitter | X</link>
                        <link url="https://facebook.com/">Facebook</link>
                    </socials>
                    <favourites>
                        <weapon>
                            <name>Phantom</name>
                            <skin src="server/iamge" upgraded="yes">Prime</skin>
                        </weapon>
                        <agent>Jett</agent>
                        <mouse type="ambidextrous">Logitech G Pro</mouse>
                        <keyboard>Logitech G Pro</keyboard>
                        <monitor model="XL2546">
                            <name>BenQ Zowie</name>
                            <size>27"</size>
                            <panel sync_tech="G-Sync">IPS</panel>
                            <resolution>2560 x 1440</resolution>
                            <refresh_rate>240Hz</refresh_rate>
                        </monitor>
                    </favourites>
                    <experience>562354</experience>
                </player>
            </players>
        </team>
        <team id="team-2">
            <name>Team 2</name>
            <players>
                <player id="player-3" active="yes">
                    <username gametag="2424">Player 3</username>
                    <player_rank division="1">Immortal</player_rank>
                    <server avg_ping="10">EU</server>
                    <personal_info access="prohibited">
                        <fullname>Kevin Chisholm</fullname>
                        <age>22</age>
                        <country>France</country>
                    </personal_info>
                    <socials>
                        <link url="https://instagram.com/">Instagram</link>
                    </socials>
                    <favourites>
                        <agent>Phenix</agent>
                        <keyboard>Logitech G Pro Light</keyboard>
                    </favourites>
                    <experience>562354</experience>
                </player>
                <player id="player-4" active="yes">
                    <username gametag="5233">Player 4</username>
                    <player_rank division="2">Platinum</player_rank>
                    <server avg_ping="50">US</server>
                    <personal_info access="free">
                        <fullname>Gyasi Linje</fullname>
                        <age>22</age>
                        <country>England</country>
                    </personal_info>
                    <favourites>
                        <weapon>
                            <name>Vandal</name>
                        </weapon>
                    </favourites>
                    <experience>83583</experience>
                </player>
            </players>
        </team>
    </teams>
    <tournaments>
        <tournament>
            <name>Valorant Masters<edition>1</edition>
            </name>
            <location>Reykjavik, Iceland</location>
            <date>
                <start>2021-05-24</start>
                <end>2021-05-30</end>
            </date>
            <prize_pool currency="PLN">600000</prize_pool>
            <teams>
                <team id="team_1">
                    <name>Team 1</name>
                </team>
                <team id="team_2">
                    <name>Team 2</name>
                </team>
            </teams>
        </tournament>
        <tournament>
            <name>Valorant Champions<edition>2</edition>
            </name>
            <location>Berlin, Germany</location>
            <date>
                <start>2021-09-09</start>
                <end>2021-09-19</end>
            </date>
            <prize_pool currency="EUR">100000</prize_pool>
            <teams>
                <team id="team_3">
                    <name>Team 3</name>
                </team>
                <team id="team_4">
                    <name>Team 4</name>
                </team>
                <team id="team_5">
                    <name>Team 5</name>
                </team>
            </teams>
        </tournament>
    </tournaments>
</valorant_state>